### ISSUE TITLE
Autodoc libraries missing

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-tmo-optics#9]
![image](https://user-images.githubusercontent.com/10647860/105425397-2b3a6480-5bfe-11eb-95cc-e0a42869978c.png)

**Comment by klauer** [comment]
This appears to no longer be an issue:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/5139267/223514081-8e0189eb-cbb2-429d-9575-01fc801259f6.png">
